# Form implementation generated from reading ui file 'SS_form_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_SS_form_2(object):
    def setupUi(self, SS_form_2):
        SS_form_2.setObjectName("SS_form_2")
        SS_form_2.resize(394, 218)
        self.label = QtWidgets.QLabel(parent=SS_form_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 41, 20))
        self.label.setObjectName("label")
        self.le_inputText = QtWidgets.QLineEdit(parent=SS_form_2)
        self.le_inputText.setGeometry(QtCore.QRect(80, 10, 271, 26))
        self.le_inputText.setObjectName("le_inputText")
        self.pb_submitText = QtWidgets.QPushButton(parent=SS_form_2)
        self.pb_submitText.setGeometry(QtCore.QRect(280, 170, 82, 28))
        self.pb_submitText.setObjectName("pb_submitText")

        self.retranslateUi(SS_form_2)
        QtCore.QMetaObject.connectSlotsByName(SS_form_2)

    def retranslateUi(self, SS_form_2):
        _translate = QtCore.QCoreApplication.translate
        SS_form_2.setWindowTitle(_translate("SS_form_2", "Form2"))
        self.label.setText(_translate("SS_form_2", "Text:"))
        self.pb_submitText.setText(_translate("SS_form_2", "Submit"))
