# Form implementation generated from reading ui file 'SS_form_1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_SS_form_1(object):
    def setupUi(self, SS_form_1):
        SS_form_1.setObjectName("SS_form_1")
        SS_form_1.resize(395, 243)
        self.pb_changeText = QtWidgets.QPushButton(parent=SS_form_1)
        self.pb_changeText.setGeometry(QtCore.QRect(271, 200, 101, 28))
        self.pb_changeText.setObjectName("pb_changeText")
        self.lb_changedText = QtWidgets.QLabel(parent=SS_form_1)
        self.lb_changedText.setGeometry(QtCore.QRect(20, 10, 361, 20))
        self.lb_changedText.setObjectName("lb_changedText")

        self.retranslateUi(SS_form_1)
        QtCore.QMetaObject.connectSlotsByName(SS_form_1)

    def retranslateUi(self, SS_form_1):
        _translate = QtCore.QCoreApplication.translate
        SS_form_1.setWindowTitle(_translate("SS_form_1", "Form1"))
        self.pb_changeText.setText(_translate("SS_form_1", "Change Text"))
        self.lb_changedText.setText(_translate("SS_form_1", "Welcome! Click Change Text button to change text."))
